name: Update Live TFL Journey Data

on:
  schedule:
    # Runs every 9 minutes
    - cron: "*/9 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TFL data update script
        run: python update_journey_data.py
        env:
          # TFL API credentials (optional but recommended for higher rate limits)
          TFL_APP_ID: ${{ secrets.TFL_APP_ID }}
          TFL_APP_KEY: ${{ secrets.TFL_APP_KEY }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "AUTO: Update TFL journey data"
          file_pattern: live_data.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
