name: Update Live NRE Journey Data

on:
  schedule:
    # Runs every 9 minutes
    - cron: "*/9 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (including zeep)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NRE data update script
        run: python update_journey_data.py
        env:
          # Set Time Zone for accurate time calculations in the script
          TZ: Europe/London 
          # NRE LDB Token for OpenLDBWS API
          LDB_TOKEN: ${{ secrets.LDB_TOKEN }} # Uses your new token

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "AUTO: Update NRE journey data with platform info"
          file_pattern: live_data.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
